CREATE TABLE `people` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `birth_date` DATETIME NOT NULL,
  `birth_location` INT NOT NULL,
  `current_location` INT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB
PARTITION BY RANGE (YEAR(birth_date)) (
  PARTITION p0 VALUES LESS THAN (1960),
  PARTITION p1 VALUES LESS THAN (1980),
  PARTITION p2 VALUES LESS THAN (2000),
  PARTITION p3 VALUES LESS THAN (2010),
  PARTITION p4 VALUES LESS THAN (2021)
);

SELECT COUNT(*) AS count_people
FROM people
WHERE YEAR(CURDATE()) - YEAR(birth_date) BETWEEN 20 AND 29;

SELECT COUNT(*) AS count_people
FROM people PARTITION (p1, p2, p3)
WHERE YEAR(CURDATE()) - YEAR(birth_date) BETWEEN 20 AND 29;
